import os
import configparser


class IniFileReader(object):

    def __init__(self, filepath):
        """open filepath whose type is a ini format.
        and set an ini instance generated by configparser.
        """
        if not os.path.isfile(filepath):
            raise FileNotFoundError("%s doesn't exist" % filepath)
        ini = configparser.RawConfigParser()
        with open(filepath) as f:
            ini.readfp(f)
        self.ini = ini

    def values(self, name, section="DEFAULT"):
        """return a list of values."""
        rv = []
        # convert value
        for val in self.ini.get(section, name).split():
            if os.path.exists(os.path.expanduser(val)):
                val = os.path.expanduser(val)
            rv.append(val)
        return rv


MYCONF = IniFileReader("myconfig.ini")
