import os
try:
    import configparser
except ImportError:
    import ConfigParser as configparser

__all__ = ["MYCONFIGPATH", "MYCONFIG"]


class IniFileReader(object):

    def __init__(self, filepath):
        """open filepath whose type is a ini format.
        and set an ini instance generated by configparser.
        """
        if not os.path.isfile(filepath):
            raise FileNotFoundError("%s doesn't exist" % filepath)
        ini = configparser.RawConfigParser()
        with open(filepath) as f:
            ini.readfp(f)
        self.ini = ini

    def values(self, name, section="DEFAULT"):
        """return a list of values."""
        rv = []
        # convert value
        for val in self.ini.get(section, name).split():
            if os.path.exists(os.path.expanduser(val)):
                val = os.path.expanduser(val)
            rv.append(val)
        if len(rv) == 1:
            return rv[0]
        else:
            return rv

MYCONFIGPATH = os.environ.get("MYCONFIGPATH")
if MYCONFIGPATH is None:
    MYCONFIGPATH = "myconfig.ini"

if not os.path.isfile(MYCONFIGPATH):
    raise ImportError("myconfig.ini can't be imported.")
MYCONFIG = IniFileReader(MYCONFIGPATH)
