---
- name: mkdir zip directory
  file: dest={{ gae.dest|dirname }} state=directory

- name: setup google app engine
  get_url: url={{ gae.latest }} dest={{ gae.dest }} force=no
  register: result

- name: unzip the downloaded gae zip file
  unarchive: src={{ gae.dest }} dest={{ gae.dest|dirname }} copy=no creates
  when: result|changed

- name: git pull from repositories
  git: name={{ item }} dest={{ dirs.projects }}/{{ item.split("/")|last }} update=no
  with_items: repos