apiVersion: v1
kind: Config
clusters:
  - name: gke-via-proxy-gke
    cluster:
      server: http://proxy-gke:8001
contexts:
  - name: gke-via-proxy-gke
    context:
      cluster: gke-via-proxy-gke
      user: proxy-user
current-context: gke-via-proxy-gke
users:
  - name: proxy-user
    user: {}
