---

github_repos:
  - repo: https://github.com/her0e1c1/home.git
    dest: ~/github/home
  - repo: ssh://git@github.com/her0e1c1/emacs.d.git
    dest: ~/github/emacs.d
  - repo: ssh://git@github.com/her0e1c1/fabfile.git
    dest: ~/github/fabfile
  - repo: git@bitbucket.org:her0e1c1/study.git
    dest:  ~/github/study
  - repo: ssh://git@github.com/her0e1c1/samples.git
    dest: ~/github/samples
  - repo: git@bitbucket.org:her0e1c1/article.git
    dest: ~/github/article

home_files:
  - .zshrc
  - .gitconfig
  - .tmux.conf
  - .vimrc
  - ansible
  - .hgrc

repos:
  - mitsuhiko/flask.git
  - kennethreitz/requests.git
  - ansible/ansible.git
  - django/django.git
  - fabric/fabric.git
  - mitsuhiko/jinja2.git
  - pydata/pandas.git
  - numpy/numpy.git
  - paxan/python-dateutil.git
  - gruns/furl.git
  - lxml/lxml.git
  - scipy/scipy.git
  - matplotlib/matplotlib.git
  - gawel/pyquery.git
  - gorakhargosh/watchdog.git
  - paramiko/paramiko.git
  - mitsuhiko/markupsafe.git
  - Pylons/pyramid.git
  - bbangert/beaker.git
  - scikit-learn/scikit-learn.git
  - mitsuhiko/werkzeug.git
  - benoitc/gunicorn.git
  - pexpect/pexpect.git
  - ipython/ipython.git
  - zopefoundation/zope.interface.git
  - Pylons/venusian.git
  - Pylons/colander.git
  - pypa/pip.git
  - python/cpython.git
  - schacon/hg-git.git

pkg_installs:
  - vim
  - emacs24
  - tmux
  - python
  - python3
  - zsh
  - git
  #- virtualbox-ose-additions
  - wget
  - the_silver_searcher  # ag
  - sqlite3
  - devel/py-pbr  # install pip
  - devel/py-virtualenv # install virtualenv
  - mercurial
  - mysql51-server
  - mysql51-client

pip_installs:
  - sphinx
  - ipython
  - ipdb