#!/usr/bin/env python
import csv
import sys
import argparse

p = argparse.ArgumentParser()
p.add_argument("-w", dest="overwrite", action="store_true")
p.add_argument("-l", dest="lstrip", action="store_true")
p.add_argument("-d", dest="delimiter", type=str, default=",", help="Delimiter splits the input csv file")
p.add_argument("filename")
args = p.parse_args()

lines = []
with open(args.filename) as f:
    lines = [l for l in csv.reader(f, delimiter=args.delimiter)]

try:
    header = lines[0]
except IndexError:
    print("The {filename} has no header".format(filename=args.filename))
    sys.exit()

max_column_lengths = []
for col in range(len(header)):
    mlength = max([
        len(lines[row][col])
        for row in range(len(lines))
    ])
    max_column_lengths.append(mlength)

rows = []
for row in range(len(lines)):
    b = []
    for col in range(len(header)):
        cell = lines[row][col]
        if args.lstrip:
            cell = cell.strip()
            format_ = "%s"
        else:
            format_ = "%{l}s".format(l=max_column_lengths[col])
        b.append(format_ % cell)
    rows.append(b)

if args.overwrite:
    with open(args.filename, "w") as f:
        writer = csv.writer(f, delimiter=args.delimiter)
        for r in rows:
            writer.writerow(r)
else:
    for r in rows:
        print (args.delimiter.join(r))
