#!/usr/bin/env python
import argparse
import shutil
import os

p = argparse.ArgumentParser()
p.add_argument("from_")
p.add_argument("to_")
args = p.parse_args()


def chage_ext(from_, to_):
    for f in os.listdir("."):
        base, ext = os.path.splitext(f)
        if ext.endswith(from_):
            to = base + "." + to_
            shutil.move(f, to)

chage_ext(args.from_, args.to_)
