---
- hosts: localhost 
  connection: local
  vars:
    save_dir: ~/repositories
    github_dir: ~/github
    repo_home: https://github.com/her0e1c1/home.git
    repo_home_dir: ~/github/home
    repo_emacsd: ssh://git@github.com/her0e1c1/emacs.d.git
    repo_emacsd_dir: ~/github/emacs.d
    repo_fabfile: ssh://git@github.com/her0e1c1/fabfile.git
    repo_fabfile_dir: ~/github/fabfile
    repo_study: git@bitbucket.org:her0e1c1/study.git
    repo_study_dir: ~/github/study
    repo_samples: ssh://git@github.com/her0e1c1/samples.git
    repo_samples_dir: ~/github/samples
  tasks:
    - name: make a github directory
      file: dest={{ github_dir }} state=directory
    # - name: git pull home
    #   git: repo={{ github_repo_home }} dest={{ github_home_home }}
    - name: git pull at emacsd repository
      git: repo={{ repo_emacsd }} dest={{ repo_emacsd_dir }} update=no accept_hostkey=True
    - name: git pull at fabfile repository
      git: repo={{ repo_fabfile }} dest={{ repo_fabfile_dir }} update=no accept_hostkey=True
    - name: git pull at study repository
      git: repo={{ repo_study }} dest={{ repo_study_dir }} update=no accept_hostkey=True
    - name: git pull at samples repository
      git: repo={{ repo_samples }} dest={{ repo_samples_dir }} update=no accept_hostkey=True
    - name: copy fabricrc
      copy: src={{ repo_fabfile_dir }}/.fabricrc.example dest=~/.fabricrc force=no
    - name: ln -s {{ repo_home_dir }} ~/
      file: src={{ repo_home_dir }}/{{ item }} dest=~/{{ item }} state=link
      with_items:
        - .zshrc
        - .gitconfig
        - .tmux.conf
        - .vimrc
        - ansible
        - .hgrc
    - name: set emacs.d
      file: src={{ repo_emacsd_dir }}/{{ item }} dest=~/{{ item }} state=link
      with_items:
        - .emacs
        - .emacs.d
    - name: set fabfile
      file: src={{ repo_fabfile_dir }}/{{ item }} dest=~/{{ item }} state=link
      with_items:
        - fabfile
    - name: pull github repositories
      git: repo=https://github.com/{{ item }} dest={{ save_dir }}/{{ item }} update=no
      with_items:
        - mitsuhiko/flask.git
        - kennethreitz/requests.git
        - ansible/ansible.git
        - django/django.git
        - fabric/fabric.git
        - mitsuhiko/jinja2.git
        - pydata/pandas.git
        - numpy/numpy.git
        - paxan/python-dateutil.git
        - gruns/furl.git
        - lxml/lxml.git
        - scipy/scipy.git
        - matplotlib/matplotlib.git
        - gawel/pyquery.git
        - gorakhargosh/watchdog.git
        - paramiko/paramiko.git
        - mitsuhiko/markupsafe.git
        - Pylons/pyramid.git
        - bbangert/beaker.git
        - scikit-learn/scikit-learn.git
        - mitsuhiko/werkzeug.git
        - benoitc/gunicorn.git
        - pexpect/pexpect.git
        - ipython/ipython.git
        - zopefoundation/zope.interface.git
        - Pylons/venusian.git
        - Pylons/colander.git
        - pypa/pip.git
        - python/cpython.git
        - schacon/hg-git.git
    - name: download google app engine SDK
      get_url: dest={{ save_dir }}/gae.zip url=http://commondatastorage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.2.zip force=no
    - name: download python 3.4.0
      get_url: dest={{ save_dir }}/python-3.4.0.tgz url=http://www.python.org/ftp/python/3.4.0/Python-3.4.0.tgz force=no
    - name: unzip sdk
      unarchive: src={{ save_dir }}/gae.zip dest={{ save_dir }}/ copy=no
    - name: unzip python 3.4.0
      unarchive: src={{ save_dir }}/python-3.4.0.tgz dest={{ save_dir }}/ copy=no
    - name: clone mercurial repositories by git
      git: repo=http://bitbucket.org/{{ item }} dest={{ save_dir }}/{{ item }} update=no
      with_items:
        - zzzeek/sqlalchemy.git
    - name: clone mercurial repositories by git
      hg: repo=http://bitbucket.org/{{ item }} dest={{ save_dir }}/{{ item }}
      with_items:
        - birkenfeld/sphinx
        - birkenfeld/pygments-main
        - mirror/docutils

- hosts: prisoners 
  remote_user: root
  gather_facts: yes
  vars:
      ansible_python_interpreter: "/usr/local/bin/python"
  tasks:
    - name: pkg install
      pkgng: name={{ item }} state=present cached=no
      with_items:
        - vim
        - emacs24
        - tmux
        - python
        - python3
        - zsh
        - git
        #- virtualbox-ose-additions
        - wget
        - sqlite3
        - devel/py-pbr  # install pip
        - devel/py-virtualenv # install virtualenv
        - mercurial
        - mysql51-server
        - mysql51-client
    - name: mkdir ~/.ssh
      file: dest=~/.ssh state=directory mode=700
    - name: modify user root
      user: name=root state=present shell=/usr/local/bin/zsh
    - name: create user me
      user: name=me state=present password=soRQg4JUIxU3E shell=/usr/local/bin/zsh

- hosts: prisoners
  vars:
      project_home: /root/_projects/test
      github_home: ~/github
      github_repo_home: https://github.com/her0e1c1/home.git
      ansible_python_interpreter: /usr/local/bin/python
  remote_user: root
  gather_facts: no
  tasks:
    - name: mkdir project home ({{ project_home }})
      file: dest={{ project_home }} state=directory
    - name: create virtualenv
      shell: virtualenv {{ project_home }} --no-site-packages
    - name: github
      file: dest={{ github_home }} state=directory
    - name: git pull home
      git: repo={{ github_repo_home }} dest={{ github_home }}

- hosts: prisoners
  vars:
      ansible_python_interpreter: "/usr/local/bin/python"
  remote_user: root
  gather_facts: no
  tasks:
    - name: pip install
      pip: name={{ item }}
      with_items:
        - sphinx
        - ipython
        - ipdb
